apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    name: java-deployment-pod
    version: blue-env
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
